wf attempt to use the retry action to simplify the wf

diff --git a/.github/workflows/check-links.yml b/.github/workflows/check-links.yml
--- a/.github/workflows/check-links.yml
+++ b/.github/workflows/check-links.yml
@@ -51,48 +51,79 @@ jobs:
           curl https://htmltest.wjdp.uk | bash -s -- -b scripts/htmltest v0.17.0
           echo "Installation done"
           ./scripts/htmltest/htmltest --version
-      - name: Check links (1st run)
-        id: check_links_run_01
-        continue-on-error: true
-        uses: ./.github/actions/check-links-run
-        with:
-          run-number: '01'
 
-      - name: Check links (2nd run)
-        id: check_links_run_02
-        if: steps.check_links_run_01.outcome == 'failure'
-        continue-on-error: true
-        uses: ./.github/actions/check-links-run
-        with:
-          run-number: '02'
+        # TODO remove if the retry action configuration does not work as expected
+#      - name: Check links
+#        id: check_links
+#        continue-on-error: true
+#        working-directory: scripts/htmltest
+#        shell: bash
+#        run: |
+#          ./htmltest -c ./htmltest_bonita-documentation-site.yml ../../build/site
 
-      - name: Check links (3rd run)
-        id: check_links_run_03
-        if: steps.check_links_run_02.outcome == 'failure'
-        continue-on-error: true
-        uses: ./.github/actions/check-links-run
+      - name: Check links
+        id: check_links
+        uses: nick-fields/retry@v3
         with:
-          run-number: '03'
+          timeout_minutes: 15 # the first analysis takes around 7 minutes
+          max_attempts: 5
+          continue_on_error: true
+          command: /htmltest -c ./htmltest_bonita-documentation-site.yml ../../build/site
 
-      - name: Check links (4th run)
-        id: check_links_run_04
-        if: steps.check_links_run_03.outcome == 'failure'
-        continue-on-error: true
-        uses: ./.github/actions/check-links-run
+      - name: Upload links analysis
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          run-number: '04'
+          name: check-links-analysis-${{ github.sha }}
+          path: scripts/htmltest/config
 
-      - name: Check links (5th run)
-        id: check_links_run_05
-        if: steps.check_links_run_04.outcome == 'failure'
-        continue-on-error: true
-        uses: ./.github/actions/check-links-run
-        with:
-          run-number: '05'
-
-      - name: Fail workflow if 5th link check failed
-        if: steps.check_links_run_05.outcome == 'failure'
+      - name: Fail workflow if link check failed
+        if: steps.check_links.outcome == 'failure'
         run: exit 1
+
+      # TODO remove if the retry action configuration is ok
+#      - name: Check links (1st run)
+#        id: check_links_run_01
+#        continue-on-error: true
+#        uses: ./.github/actions/check-links-run
+#        with:
+#          run-number: '01'
+#
+#      - name: Check links (2nd run)
+#        id: check_links_run_02
+#        if: steps.check_links_run_01.outcome == 'failure'
+#        continue-on-error: true
+#        uses: ./.github/actions/check-links-run
+#        with:
+#          run-number: '02'
+#
+#      - name: Check links (3rd run)
+#        id: check_links_run_03
+#        if: steps.check_links_run_02.outcome == 'failure'
+#        continue-on-error: true
+#        uses: ./.github/actions/check-links-run
+#        with:
+#          run-number: '03'
+#
+#      - name: Check links (4th run)
+#        id: check_links_run_04
+#        if: steps.check_links_run_03.outcome == 'failure'
+#        continue-on-error: true
+#        uses: ./.github/actions/check-links-run
+#        with:
+#          run-number: '04'
+#
+#      - name: Check links (5th run)
+#        id: check_links_run_05
+#        if: steps.check_links_run_04.outcome == 'failure'
+#        continue-on-error: true
+#        uses: ./.github/actions/check-links-run
+#        with:
+#          run-number: '05'
+#
+#      - name: Fail workflow if 5th link check failed
+#        if: steps.check_links_run_05.outcome == 'failure'
+#        run: exit 1
 
       # This step is commented out because we don't want to send notifications to Slack for now, we can uncomment it later, when all errors will be fixed.
       # For now, we will monitor the workflow result each week manually.
